### PR TITLE
Add isSelectingDateOne to props and set isSelectingDate1 according to…

### PR DESCRIPTION
**Pull request by ElielHaouzi**
… it.

See #28
Add isSelectingDateOne to props and set isSelectingDate1 according to it.

No deprecate any API.

Second Commit: color days on hover in range already BEFORE the dateTwo is selected.

Third commit: 
On allDatesSelected let the user change the dateOne and dateTwo like airbnb datepicker

### CODE REVIEW

**Comment by MikaelEdebro** [comment]
Not sure about this one. I appreciate the effort, but I clearly write on the github page to please submit a discussion issue before starting doing any PRs. Just to avoid having people waste their time. 
"But before you start hacking away, please first create an issue where you explain what it is that you think needs to be done and why, so we can agree that the changes makes sense."

Commit 1: Could you justify why you need this?
Commit 2: On Airbnb.com (and http://airbnb.io/react-dates), the days are not colored until you have selected both dates
Commit 3: Same here, on Airbnb.com, the user can't change the second date, only first date. And this is already the logic of the datepicker.

**Comment by ElielHaouzi** [comment]
Hi,
Thank you for your reply

Commit 1, 
In https://www.airbnb.com/a (this is their landing page from google adwords) when you select the check in, the check out is automatically open and when you click on 
one date in the check out this is for the second date directly since you already choose the date on in the check in.
I need the same behavior.

Commit 2:
ezgif com-video-to-gif

**Comment by MikaelEdebro** [comment]
Regarding commit 2. This is how it looks for me (Windows, latest Chrome):
airbnb
What browser/OS are you using?

**Comment by ElielHaouzi** [comment]
OK weird..

I am using Chrome on Ubuntu

**Pull request closed without merging**
